# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e69c202e8967a9c9796b76db313a579af946f48ccc2098f1ee4908d665b2559de835b82c91ab7d50039e2ba9deff4b3f2eb1ddd0b578ed99877aee104e4b34d8

test:
  secret_key_base: 996694befd3f4b767f1924bc86d0e4e66b5007f5a3264447e281b274f365120d9128cbc7b21e9bfc1b4d2ea32cc72b9b55ca1a1777789a43919ffb979ad4656d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
